apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedbilal-7191/flask-application.git
    targetRevision: HEAD
    path: helm-chart          # path to your Helm chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
